export const SCREEN_AUTHENTICATION = "Authentification"
export const SCREEN_REGISTRATION = "Inscription"
export const SCREEN_LOG_IN = "Connexion"
export const SCREEN_RESET_PASSWORD = "Réinitialisation"
export const SCREEN_HOME = "Accueil"
export const SCREEN_EVENTS = "Événements"